// src/lib/components/ActivityExperience.svelte
<script lang="ts">
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'; import Blocks from '@lucide/svelte/icons/blocks'; import Users from '@lucide/svelte/icons/users';
  import type { CourseWeek } from '$lib/course'; import MathText from './MathText.svelte'; import SiteHeader from './SiteHeader.svelte'; import ThingsInRings from './ThingsInRings.svelte';
  let { courseWeek }:{courseWeek:CourseWeek}=$props();
</script>

<main class="min-h-screen bg-base-200/50"><SiteHeader compact/><div class="mx-auto max-w-6xl px-5 py-10">
  <a href="/courses/math-for-designer" class="btn btn-ghost btn-sm -ml-3 mb-6"><ArrowLeft size={16}/> Course</a>
  <header class="mb-8"><p class="eyebrow">Week {courseWeek.week} studio</p><h1 class="display-title mt-2 text-4xl font-black tracking-[-.04em] md:text-6xl">{courseWeek.title} activities</h1></header>
  {#if courseWeek.week===1}<ThingsInRings/>{/if}
  {#if courseWeek.activity.length}
    <div class="mt-8 space-y-6">{#each courseWeek.activity as activity, index}<section class="interactive-card"><p class="eyebrow">Activity {index+1}</p><h2 class="mt-2 text-3xl font-extrabold">{activity.title}</h2><div class="mt-5"><MathText content={activity.content} numberingPrefix={`${courseWeek.week}.A${index+1}`}/></div></section>{/each}</div>
  {:else if courseWeek.week!==1}
    <section class="activity-placeholder"><div class="grid h-20 w-20 place-items-center rounded-3xl bg-primary/10 text-primary"><Blocks size={38}/></div><h2 class="display-title mt-6 text-4xl font-black">Studio activity coming soon</h2><p class="mt-4 max-w-xl text-lg leading-8 text-base-content/65">This week does not yet include an activity section in the source lecture.</p><div class="alert mt-7 max-w-xl"><Users/><span>The lecture and worksheet remain available while this activity is prepared.</span></div></section>
  {/if}
</div></main>

// app/components/ActivityExperience.tsx
import Link from "next/link";
import { ArrowLeft, Blocks, Users } from "lucide-react";
import type { CourseWeek } from "../lib";
import { SiteHeader } from "./SiteHeader";
import { ThingsInRings } from "./ThingsInRings";

export function ActivityExperience({ courseWeek }: { courseWeek: CourseWeek }) {
  return <main className="min-h-screen bg-base-200/50"><SiteHeader compact/><div className="mx-auto max-w-6xl px-5 py-10"><Link href="/course" className="btn btn-ghost btn-sm -ml-3 mb-6"><ArrowLeft size={16}/> Course</Link>{courseWeek.week === 1 ? <ThingsInRings/> : <section className="activity-placeholder"><div className="grid h-20 w-20 place-items-center rounded-3xl bg-primary/10 text-primary"><Blocks size={38}/></div><p className="eyebrow mt-6">Week {courseWeek.week} studio</p><h1 className="display-title mt-2 text-5xl font-black">{courseWeek.title} lab</h1><p className="mt-4 max-w-xl text-lg leading-8 text-base-content/65">A guided group activity that turns this week’s ideas into something you can move, test, and discuss together.</p><div className="alert mt-7 max-w-xl"><Users/><span>Activity instructions are ready for classroom facilitation. Interactive materials will be added in the next course release.</span></div></section>}</div></main>;
}
