// src/lib/components/MathText.svelte
<script lang="ts">
  import katex from 'katex';
  let { content }: { content: string } = $props();
  const escape = (value: string) => value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!);
  const inline = (value: string) => value.split(/(\$[^$\n]+\$)/g).map((part) => part.startsWith('$') && part.endsWith('$') ? katex.renderToString(part.slice(1, -1), { throwOnError: false }) : escape(part)).join('');
  function render(value: string) {
    return value.split(/(\\\[[\s\S]*?\\\]|\\begin\{(?:align\*?|equation\*?|eqnarray\*?|split|array)\}[\s\S]*?\\end\{(?:align\*?|equation\*?|eqnarray\*?|split|array)\})/g).map((segment) => {
      const block = segment.match(/^\\\[([\s\S]*)\\\]$/) || segment.match(/^\\begin\{[^}]+\}([\s\S]*)\\end\{[^}]+\}$/);
      if (block) return `<div class="math-scroll">${katex.renderToString(block[1], { throwOnError: false, displayMode: true })}</div>`;
      return segment.split(/\n+/).map((line) => line.trim()).filter((line) => line && line !== '{}' && !line.startsWith('[Interactive diagram')).map((line) => line.startsWith('- ') ? `<div class="lesson-bullet"><span></span>${inline(line.slice(2))}</div>` : `<p>${inline(line)}</p>`).join('');
    }).join('');
  }
</script>

<div class="lesson-copy">{@html render(content)}</div>

// app/components/MathText.tsx
"use client";

import { BlockMath, InlineMath } from "react-katex";

function renderInline(text: string, key: string) {
  const pieces = text.split(/(\$[^$\n]+\$)/g);
  return pieces.map((piece, index) => piece.startsWith("$") && piece.endsWith("$")
    ? <InlineMath key={`${key}-${index}`} math={piece.slice(1, -1)} errorColor="#e64980" renderError={() => <code>{piece}</code>} />
    : <span key={`${key}-${index}`}>{piece}</span>);
}

export function MathText({ content }: { content: string }) {
  const segments = content.split(/(\\\[[\s\S]*?\\\]|\\begin\{(?:align\*?|equation\*?|eqnarray\*?|split|array)\}[\s\S]*?\\end\{(?:align\*?|equation\*?|eqnarray\*?|split|array)\})/g);
  return (
    <div className="lesson-copy">
      {segments.map((segment, index) => {
        const block = segment.match(/^\\\[([\s\S]*)\\\]$/) || segment.match(/^\\begin\{[^}]+\}([\s\S]*)\\end\{[^}]+\}$/);
        if (block) return <div className="math-scroll" key={index}><BlockMath math={block[1]} errorColor="#e64980" renderError={() => <pre>{segment}</pre>} /></div>;
        return segment.split(/\n+/).filter(Boolean).map((line, lineIndex) => {
          const clean = line.replace(/^\s*\{\}\s*$/, "").trim();
          if (!clean) return null;
          if (clean.startsWith("- ")) return <div className="lesson-bullet" key={`${index}-${lineIndex}`}><span />{renderInline(clean.slice(2), `${index}-${lineIndex}`)}</div>;
          if (clean.startsWith("[Interactive diagram")) return null;
          return <p key={`${index}-${lineIndex}`}>{renderInline(clean, `${index}-${lineIndex}`)}</p>;
        });
      })}
    </div>
  );
}
