// app/components/LectureExperience.tsx
"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, ChevronLeft, LockKeyhole, Menu, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { CourseWeek } from "../lib";
import { MathText } from "./MathText";
import { ProgressRing } from "./ProgressRing";
import { ThemeToggle } from "./ThemeToggle";
import { InteractiveGraph } from "./InteractiveGraph";

export function LectureExperience({ courseWeek }: { courseWeek: CourseWeek }) {
  const [active, setActive] = useState(0);
  const [unlocked, setUnlocked] = useState(0);
  const [selected, setSelected] = useState<string | null>(null);
  const [feedback, setFeedback] = useState<"correct" | "wrong" | null>(null);
  const [menu, setMenu] = useState(false);
  const sections = courseWeek.sections;
  const progress = Math.round(((unlocked + 1) / sections.length) * 100);
  const choices = useMemo(() => {
    const correct = sections[active].title;
    const others = sections.map((section) => section.title).filter((title) => title !== correct).slice(0, 3);
    const generic = ["A different mathematical model", "Historical background", "Visual composition"];
    return [correct, ...others, ...generic].slice(0, 3).sort((a, b) => (a.charCodeAt(0) + active) % 3 - (b.charCodeAt(0) + active) % 3);
  }, [active, sections]);

  useEffect(() => {
    const saved = Number(localStorage.getItem(`mfd-progress-${courseWeek.week}`) || 0);
    setUnlocked(Math.min(saved, sections.length - 1));
    setActive(Math.min(saved, sections.length - 1));
  }, [courseWeek.week, sections.length]);

  const go = (index: number) => {
    if (index > unlocked) return;
    setActive(index); setSelected(null); setFeedback(null); setMenu(false); window.scrollTo({ top: 0, behavior: "smooth" });
  };
  const check = () => {
    if (!selected) return;
    const correct = selected === sections[active].title;
    setFeedback(correct ? "correct" : "wrong");
    if (correct && active < sections.length - 1) {
      const next = Math.max(unlocked, active + 1);
      setUnlocked(next); localStorage.setItem(`mfd-progress-${courseWeek.week}`, String(next));
    }
  };
  const next = () => { if (feedback === "correct" && active < sections.length - 1) go(active + 1); };

  return (
    <div className="min-h-screen bg-base-100">
      <div className="fixed inset-x-0 top-0 z-50 h-1 bg-base-300"><div className="h-full bg-primary transition-all" style={{ width: `${progress}%` }}/></div>
      <header className="sticky top-0 z-40 flex h-16 items-center border-b border-base-300 bg-base-100/95 px-3 backdrop-blur md:px-5">
        <button className="btn btn-ghost btn-circle lg:hidden" onClick={() => setMenu(true)} aria-label="Open section menu"><Menu/></button>
        <Link className="btn btn-ghost gap-2" href="/course"><ChevronLeft size={18}/><span className="hidden sm:inline">Course</span></Link>
        <div className="min-w-0 flex-1 text-center"><p className="truncate text-xs font-bold uppercase tracking-[.14em] text-base-content/45">Week {courseWeek.week}</p><h1 className="truncate font-extrabold">{courseWeek.title}</h1></div>
        <div className="flex items-center gap-2"><ProgressRing value={progress}/><ThemeToggle/></div>
      </header>
      <div className="mx-auto flex max-w-[1500px]">
        <aside className={`lesson-sidebar ${menu ? "is-open" : ""}`}>
          <div className="flex items-center justify-between p-5 lg:hidden"><b>Sections</b><button className="btn btn-ghost btn-circle" onClick={() => setMenu(false)}><X/></button></div>
          <div className="p-5"><p className="eyebrow">In this lecture</p><nav className="mt-3 space-y-1">
            {sections.map((section, index) => <button key={section.title} className={`section-link ${active === index ? "active" : ""}`} disabled={index > unlocked} onClick={() => go(index)}><span>{index < unlocked ? <Check size={15}/> : index > unlocked ? <LockKeyhole size={14}/> : index + 1}</span><span>{section.title}</span></button>)}
          </nav></div>
          <div className="mt-auto border-t border-base-300 p-5"><div className="text-sm font-semibold">Need more practice?</div><Link className="link link-primary mt-1 text-sm" href={`/course/worksheet/${courseWeek.week}`}>Open the worksheet →</Link></div>
        </aside>
        {menu && <button className="fixed inset-0 z-40 bg-black/30 lg:hidden" onClick={() => setMenu(false)} aria-label="Close menu"/>}
        <main className="min-w-0 flex-1 px-5 py-9 md:px-10 lg:px-16">
          <article className="mx-auto max-w-[760px]">
            <div className="mb-8"><p className="eyebrow">Section {active + 1} of {sections.length}</p><h2 className="display-title mt-2 text-4xl font-black tracking-[-.035em] md:text-5xl">{sections[active].title}</h2></div>
            <MathText content={sections[active].content}/>
            {courseWeek.week >= 3 && courseWeek.week <= 8 && active === 0 && <InteractiveGraph week={courseWeek.week}/>} 
            <section className="checkpoint mt-12">
              <div className="mb-1 text-sm font-black uppercase tracking-[.14em] text-primary">Checkpoint</div>
              <h3 className="text-2xl font-extrabold">What was the central idea of this section?</h3>
              <div className="mt-5 grid gap-3">{choices.map((choice) => <button key={choice} onClick={() => { setSelected(choice); setFeedback(null); }} className={`answer-choice ${selected === choice ? "selected" : ""}`}>{choice}</button>)}</div>
              {feedback && <div className={`alert mt-4 ${feedback === "correct" ? "alert-success" : "alert-error"}`}><span>{feedback === "correct" ? "Exactly — the next section is now open." : "Not quite. Revisit the heading and try once more."}</span></div>}
              <div className="mt-5 flex justify-between"><button className="btn btn-ghost" disabled={active === 0} onClick={() => go(active - 1)}><ArrowLeft/> Back</button>{feedback === "correct" && active < sections.length - 1 ? <button className="btn btn-primary rounded-full px-6" onClick={next}>Continue <ArrowRight/></button> : active === sections.length - 1 && feedback === "correct" ? <Link className="btn btn-primary rounded-full" href={`/course/worksheet/${courseWeek.week}`}>Start worksheet <ArrowRight/></Link> : <button className="btn btn-primary rounded-full px-6" disabled={!selected} onClick={check}>Check answer</button>}</div>
            </section>
          </article>
        </main>
      </div>
    </div>
  );
}

// src/lib/components/LectureExperience.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'; import ArrowRight from '@lucide/svelte/icons/arrow-right'; import Check from '@lucide/svelte/icons/check'; import ChevronLeft from '@lucide/svelte/icons/chevron-left'; import LockKeyhole from '@lucide/svelte/icons/lock-keyhole'; import Menu from '@lucide/svelte/icons/menu'; import X from '@lucide/svelte/icons/x';
  import type { CourseWeek } from '$lib/course';
  import MathText from './MathText.svelte'; import ThemeToggle from './ThemeToggle.svelte'; import InteractiveGraph from './InteractiveGraph.svelte';
  let { courseWeek }: { courseWeek: CourseWeek } = $props();
  let active = $state(0), unlocked = $state(0), selected = $state<string|null>(null), feedback = $state<'correct'|'wrong'|null>(null), menu = $state(false);
  let sections = $derived(courseWeek.sections);
  let progress = $derived(Math.round(((unlocked + 1) / sections.length) * 100));
  let choices = $derived.by(() => {
    const correct = sections[active].title;
    const others = sections.map((section) => section.title).filter((title) => title !== correct).slice(0, 2);
    return [correct, ...others, 'A different mathematical model', 'Historical background'].slice(0, 3).sort((a,b) => (a.charCodeAt(0)+active)%3-(b.charCodeAt(0)+active)%3);
  });
  onMount(() => { const saved = Number(localStorage.getItem(`mfd-progress-${courseWeek.week}`) || 0); unlocked = Math.min(saved, sections.length - 1); active = unlocked; });
  function go(index: number) { if (index > unlocked) return; active=index; selected=null; feedback=null; menu=false; window.scrollTo({top:0,behavior:'smooth'}); }
  function check() { if (!selected) return; const correct=selected===sections[active].title; feedback=correct?'correct':'wrong'; if(correct && active<sections.length-1){unlocked=Math.max(unlocked,active+1); localStorage.setItem(`mfd-progress-${courseWeek.week}`,String(unlocked));} }
</script>

<div class="min-h-screen bg-base-100">
  <div class="fixed inset-x-0 top-0 z-50 h-1 bg-base-300"><div class="h-full bg-primary transition-all" style={`width:${progress}%`}></div></div>
  <header class="sticky top-0 z-40 flex h-16 items-center border-b border-base-300 bg-base-100/95 px-3 backdrop-blur md:px-5">
    <button class="btn btn-ghost btn-circle lg:hidden" onclick={() => menu=true} aria-label="Open section menu"><Menu/></button>
    <a class="btn btn-ghost gap-2" href="/course"><ChevronLeft size={18}/><span class="hidden sm:inline">Course</span></a>
    <div class="min-w-0 flex-1 text-center"><p class="truncate text-xs font-bold uppercase tracking-[.14em] text-base-content/45">Week {courseWeek.week}</p><h1 class="truncate font-extrabold">{courseWeek.title}</h1></div>
    <div class="flex items-center gap-2"><div class="radial-progress text-primary" style={`--value:${progress};--size:3rem;--thickness:4px`} role="progressbar" aria-label={`${progress}% complete`}><span class="text-xs font-bold">{progress}%</span></div><ThemeToggle/></div>
  </header>
  <div class="mx-auto flex max-w-[1500px]">
    <aside class={`lesson-sidebar ${menu?'is-open':''}`}>
      <div class="flex items-center justify-between p-5 lg:hidden"><b>Sections</b><button class="btn btn-ghost btn-circle" onclick={() => menu=false}><X/></button></div>
      <div class="p-5"><p class="eyebrow">In this lecture</p><nav class="mt-3 space-y-1">
        {#each sections as section, index}<button class:active={active===index} class="section-link" disabled={index>unlocked} onclick={() => go(index)}><span>{#if index<unlocked}<Check size={15}/>{:else if index>unlocked}<LockKeyhole size={14}/>{:else}{index+1}{/if}</span><span>{section.title}</span></button>{/each}
      </nav></div>
      <div class="mt-auto border-t border-base-300 p-5"><div class="text-sm font-semibold">Need more practice?</div><a class="link link-primary mt-1 text-sm" href={`/course/worksheet/${courseWeek.week}`}>Open the worksheet →</a></div>
    </aside>
    {#if menu}<button class="fixed inset-0 z-40 bg-black/30 lg:hidden" onclick={() => menu=false} aria-label="Close menu"></button>{/if}
    <main class="min-w-0 flex-1 px-5 py-9 md:px-10 lg:px-16"><article class="mx-auto max-w-[760px]">
      <div class="mb-8"><p class="eyebrow">Section {active+1} of {sections.length}</p><h2 class="display-title mt-2 text-4xl font-black tracking-[-.035em] md:text-5xl">{sections[active].title}</h2></div>
      <MathText content={sections[active].content}/>
      {#if courseWeek.week>=3 && courseWeek.week<=8 && active===0}<InteractiveGraph week={courseWeek.week}/>{/if}
      <section class="checkpoint mt-12"><div class="mb-1 text-sm font-black uppercase tracking-[.14em] text-primary">Checkpoint</div><h3 class="text-2xl font-extrabold">What was the central idea of this section?</h3>
        <div class="mt-5 grid gap-3">{#each choices as choice}<button onclick={() => {selected=choice;feedback=null}} class:selected={selected===choice} class="answer-choice">{choice}</button>{/each}</div>
        {#if feedback}<div class={`alert mt-4 ${feedback==='correct'?'alert-success':'alert-error'}`}><span>{feedback==='correct'?'Exactly — the next section is now open.':'Not quite. Revisit the heading and try once more.'}</span></div>{/if}
        <div class="mt-5 flex justify-between"><button class="btn btn-ghost" disabled={active===0} onclick={() => go(active-1)}><ArrowLeft/> Back</button>
          {#if feedback==='correct' && active<sections.length-1}<button class="btn btn-primary rounded-full px-6" onclick={() => go(active+1)}>Continue <ArrowRight/></button>{:else if active===sections.length-1 && feedback==='correct'}<a class="btn btn-primary rounded-full" href={`/course/worksheet/${courseWeek.week}`}>Start worksheet <ArrowRight/></a>{:else}<button class="btn btn-primary rounded-full px-6" disabled={!selected} onclick={check}>Check answer</button>{/if}
        </div>
      </section>
    </article></main>
  </div>
</div>
