// app/components/ThemeToggle.tsx
"use client";

import { Moon, Sun } from "lucide-react";
import { useEffect, useState } from "react";

export function ThemeToggle() {
  const [dark, setDark] = useState(false);
  useEffect(() => {
    const saved = localStorage.getItem("mfd-theme");
    const next = saved ? saved === "night" : matchMedia("(prefers-color-scheme: dark)").matches;
    setDark(next);
    document.documentElement.dataset.theme = next ? "night" : "mfdlight";
  }, []);
  const toggle = () => {
    const next = !dark;
    setDark(next);
    document.documentElement.dataset.theme = next ? "night" : "mfdlight";
    localStorage.setItem("mfd-theme", next ? "night" : "mfdlight");
  };
  return (
    <button className="btn btn-ghost btn-circle" onClick={toggle} aria-label={`Switch to ${dark ? "light" : "dark"} mode`}>
      {dark ? <Sun size={19} /> : <Moon size={19} />}
    </button>
  );
}

// src/lib/components/ThemeToggle.svelte
<script lang="ts">
  import Moon from '@lucide/svelte/icons/moon'; import Sun from '@lucide/svelte/icons/sun';
  import { onMount } from 'svelte';
  let dark = false;
  onMount(() => {
    const saved = localStorage.getItem('mfd-theme');
    dark = saved ? saved === 'night' : matchMedia('(prefers-color-scheme: dark)').matches;
    document.documentElement.dataset.theme = dark ? 'night' : 'mfdlight';
  });
  function toggle() {
    dark = !dark;
    document.documentElement.dataset.theme = dark ? 'night' : 'mfdlight';
    localStorage.setItem('mfd-theme', dark ? 'night' : 'mfdlight');
  }
</script>

<button class="btn btn-ghost btn-circle" onclick={toggle} aria-label={`Switch to ${dark ? 'light' : 'dark'} mode`}>
  {#if dark}<Sun size={19}/>{:else}<Moon size={19}/>{/if}
</button>
